### ISSUE TITLE
Canastas 1T21

### ISSUE THREAD

**Issue by enadianet** [pablinte/EPH#36]
Hola, estoy usando el paquete EPH para calcular pobreza para el primer trimestre 2021, pero me salen todas las tasas iguales a cero, eso es porque no están cargadas aún las canastas regionales para ese período, quiero saber cómo puedo cargarlas o bien si lo van a actualizar ustedes. Muchas gracias.

**Comment by DiegoKoz** [comment]
@pablotis @Guidowe @natsushok algune puede actualizar la data de las canastas?

**Comment by Guidowe** [comment]
Lo veo

**Comment by Guidowe** [comment]
@enadianet ahí agregué las canastas regionales

**Comment by enadianet** [comment]
Gracias Guido!

**Comment by enadianet** [comment]
Quiero aprovechar y preguntar dos cosas más. ¿Cómo puedo calcular los errores de estimación con el paquete eph ? Por otra parte, Guido habías dicho que estaba en desarrollo la posibilidad de calcular pobreza pero a nivel semestral, como lo hace el INDEC, eso estará disponible?. Gracias.

**Comment by Guidowe** [comment]
Hola. Ambas cosas que preguntás se encuentran en la versión en desarrollo, que se instala desde github. Por ahora  lo que hay allí es lo que tenemos disponible.
Saludos, 
Guido
