### ISSUE TITLE
Problemas con `get_microdata()`

### ISSUE THREAD

**Issue by mateosuster** [pablinte/EPH#38]
Buenas! Me saltan unos errores a la hora de intentar descargar la EPH para 2019, tanto para los 4 trimestres, como uno en particular. Copio a continuación lo que me saltó en la consola. Lo que me parece raro es que ayer me andaba...

![image](https://user-images.githubusercontent.com/56704115/140085573-6e938d57-20c6-4b0d-a292-994e508c630a.png)

Aprovecho para comentar que también me apareció un problema ya contemplado en un issue anterior, sobre la imposibilidad de unir las bases a lo largo del tiempo por los diferentes tipos de variables (esto me ocurrió para los trimestres de 2020): 

`
Error: Can't combine `..1$PP04B_COD` <character> and `..3$PP04B_COD` <double>.
`

Saludos !

**Comment by mateosuster** [comment]
Con respecto al primer problema, creo que metí alguna variable errónea o mal tipeada en el vector de variables, dado que lo modifiqué y funcionó...

**Comment by pablotis** [comment]
Hola @mateosuster, ya debería estar funcionando la descarga de una serie de bases. Avísanos si ya no salta error y cerramos el issue. Muchas gracias!!

**Comment by mateosuster** [comment]
Excelente! Muchas gracias!!!
