### ISSUE TITLE
Armar paneles en la EPH

### ISSUE THREAD

**Issue by Azulchinca** [pablinte/EPH#44]
Hola! Es posible armar paneles cortos en la EPH? Es decir, la EPH primero encuesta dos trimestres a un grupo de personas, luego ese grupo se retira por dos trimestres y vuelve el año siguiente otros dos trimestres más. Por lo que se podría construir un "panel corto" con dos observaciones en un año para un mismo individo y dos observaciones en el siguiente año para el mismo individuo. De esta forma podría estudiar como cambia alguna característica particular de ese individuo de forma interanual. 
Entiendo que uno puede "invocar" las eph con el panel 

`data-> get_microdata(year=2018:2019, trimester = 1:2, type = "individual") `

De esta forma tengo datos del primer semestre

Sin embargo, hay forma de ubicar unicamente a los individuos que tengan datos en los dos años para el primer semestre?

Desde ya muchas gracias!

**Comment by pablotis** [comment]
Hola @Azulchinca! Fijate que en la sección "Get Started" de la página del paquete ([acá](https://holatam.github.io/eph/articles/eph.html)) hay un ejemplo de cómo armar un panel de trimestres consecutivos en la eph con la función  `organize_panels()`.

Cierro el issue, avisanos si no es exactamente lo que estabas buscando y vemos cómo ayudarte 💪
