### ISSUE TITLE
Problemas con AGLOMERADO

### ISSUE THREAD

**Issue by zaratepablo** [pablinte/EPH#45]
Hola!

Estoy teniendo problemas con la variable AGLOMERADO para la EPH de 2003 a 2006. Solo me aparecen 8 de los aglomerados urbanos (Gran La Plata, Gran Rosario, Gran Mendoza, Gran Cordoba, Gran Tucuman - T. Viejo, Ciudad de Buenos Aires, Partidos del GBA y Mar del Plata - Batan), el resto me aparece con un valor de 0. Esto pasa para las observaciones de 2003 T3 a 2006 T2 inclusive, pero desde el 2006 T3 en adelante me aparece todo en orden.

No creo que lo esté bajando mal, pero va mi código por las dudas:

````
library(eph)
library(dplyr)
library(tidyr)
library(haven)
library(foreign)

df <- get_microdata(year=2003:2021, trimester=1:4,type="individual") %>% 
    		unnest() %>% 
		organize_labels(., type='individual') %>% 
		as.data.frame()
````

Gracias!

**Comment by pablotis** [comment]
Hola @zaratepablo, fijate [acá](https://github.com/holatam/eph/issues/27) que hubo una consulta similar y entiendo fue saldada. 
Cierro el issue y si es necesario volvemos a abrirlo.

Gracias!
