### ISSUE TITLE
Canastas regionales

### ISSUE THREAD

**Issue by enadianet** [pablinte/EPH#63]
Hola Diego, buen día. Podrían cargar las canastas regionales para poder usar el paquete EPH? Ya se publicó hasta las del 3er trimestre 2023 y en el paquete solo está hasta el 2do. Saludos y muchas gracias.

**Comment by enadianet** [comment]
Perdón, ya están publicadas hasta el 4to trimestre 23

**Comment by caropradier** [comment]
Ya están subidas. Siempre estás invitado a hacer un pull request cuando quieras aportar al paquete

**Comment by enadianet** [comment]
Hola, muchas gracias. No se bien lo que significa hacer un pull request pero veré de averiguarlo. Muchas gracias.
